### ISSUE TITLE
Move all Discord functionality to nodes

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#123]
Right now we have a lot of hardcoded discord functionality. Ideally the Discord part is extremely thin and we have nodes to handle most of the stuff happening.

- Determining when the agent is being talked to, to respond should all be moved to a node
- Generate voice audio file should all be broken to nodes
  - that means audio input, text to speech from audio, generation of file, output back to discord voice

Any functionality that is hardcoded and should be configurable inside of a graph should be turned into nodes and moved, basically. If we can make these nodes common to other connectors as well, that'd be ideal :)

**Comment by fire** [comment]
I did some design for this. Free free to edit this comment.

## What is the Context and Problem Statement this is trying to solve?

Discord functionality is hard coded.

## Describe the proposed option and how it helps to overcome the problem or limitation

The Discord part is made small.

Extract the non-discord usage to other nodes.

## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams.

Extract nodes:

1. Determining when the agent is being talked to, to respond
2. Generate voice audio file
  3. audio input
  4. text to speech from audio
  5. generation of file
6. output back to discord voice

Any functionality that is hardcoded and should be configurable inside of a graph should be turned into nodes and moved. 

Stetch goal: Make these nodes common to other connectors

## Is there a reason why this should be core and done by us?

Discord is core plugin.

## Negative Consequences

Developer onboard will be harder because there's more nodes. Do we have presets?

## Positive Consequences

1. Allows extending to other voice platforms

**Comment by fire** [comment]
See also Handle images and image data #361
