### ISSUE TITLE
Add BananaML models as nodes

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#127]
- Add Whisper as STT node
- change image generation from automatic1111 to banana
- add carrot for image reco
- any other interesting models? galactica?

**Comment by fire** [comment]
We are closing this issue for the following reasons:

1. **Time since creation**: The issue was created in February, and it has been several months without significant progress or updates.
2. **Lack of design**: There is currently no design available for implementing these features, which makes it difficult to move forward with development.
3. **Task complexity**: Each task within this issue requires 3-4 subtasks, making it a complex and time-consuming endeavor.
4. **Current process alignment**: In our current development process, we have a dedicated section on how to test new features. This ensures that any new additions are thoroughly tested before being integrated into the main project.
5. **Not part of Milestone 1.5**: We have decided not to include these features in the upcoming Milestone 1.5, allowing us to focus on other priorities.

Although we still want to implement these features in the future, we believe it's best to close this issue for now and revisit it when we have a more concrete design and a better understanding of the tasks involved. This will allow us to allocate our resources more effectively and focus on other priorities in the meantime.

Once we're ready to tackle these features again, we can create new, more focused issues for each task, ensuring that they align with our current development process and testing standards.
