### ISSUE TITLE
Mobile / responsive UI and controls

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#131]
We want the app to load and be accessible and workable on a mobile device.
- Make sure all navigation works
- scale everything in css responsively
- Offer a portrait mode starting graph view
- any way to make this experience better?

**Comment by michaelsharpe** [comment]
@lalalune We should detail at what size we want this.  I don't think we could do much to allow graph edition on a phone without a huge amount of work.  Other screens like agent manager, etc., could probably be mobile responsive down to phone size.  At a breakpoint, we could hide the spell composer icon so that it becomes more about management on mobile.

I would set a minimum size of a landscape tablet at this point for use with the spell composer.  The more important point to start is that touch events work on everything.

A note here is that i think this is a pretty big undertaking, both in terms of making the whole design responsive and ensuring everything works with touch events.
