### ISSUE TITLE
[BUG] Node drops down where mouse is, not where first click happened

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#152]
This is a regression with the new react context menu.  The node is dropping down where the mouse is in the context menu when selecting.  It should drop down where the person first clicks their mouse to open the menu.

This was fixed in my fork of the original plugin here:

https://github.com/Oneirocom/context-menu-plugin

**Comment by lalalune** [comment]
@FabriceIRANKUNDA 
Check this out: https://github.com/retejs/context-menu-plugin/commit/9077af8419e33c3779566bc43f51becb8a9b8e12#diff-dc932aaf4a7be073787bf570873320eaf645b545cd7a3ac47cf6e3186bcaeb1a

Basically the node appears at the wrong place. It was working because @michaelsharpe had added some code to track the [x, y] and create it where we first clicked, not where we end up clicking at the end.
