### ISSUE TITLE
Connector simulator

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#48]
Playtesting with the conversational VRM or with the playtest window for agents is a pain, as we have to add a bunch of raw config to the "data" dropdown, which is just a temporary hack to pass more complicated data out.

It would be awesome if we had a dropdown with preset data for different connectors (discord, twitter, etc) which would make it really easy to test each of them as the data comes through the pipe.

**Comment by lalalune** [comment]
Playtest needs to be redesigned--

- [Data] button is a dropdown
  -  [custom] option to enter own data as it is now
  - Default spell comes with default playtest data so users understand how to test
  - Default playtest UI which has form fields and a feedback, similar to now but unified data/chat input
  - plugins can add a custom copmponent to override the playtest window
 
Instead of trying to force a whole bunch of paradigms, letting each plugin add an event input type and custom playtest window will be easier to manage as a good UX IMO

**Comment by michaelsharpe** [comment]
Notes for myself:

- update spellManager to expose runComponent
- create a new run methpd on the spellRunner service
- spellRunner run method will trigger off a chgain from a specific node
- create a stubbed our data object for each node before running.  Figure out a way to attach this to the component being run to be automatically gotten by the playtest window
- move allowed methods into service export

**Comment by lalalune** [comment]
We want to add three datatypes to start

Event input -- this is the current behavior -- sends a JSON object to the input, whatever is typed into the playtest goes out as the "content" field
String input -- sends whatever is typed directly to the input
Custom Data -- sends whatever data is in the "Data" tab

Parzival: We should also have data presets for different connectors I think. People should never have to open the data tab except perhaps for using the rest connector.

**Comment by michaelsharpe** [comment]
totally agreed on data presets for all of them.  And making your own data preset should eventually be thing.
