### ISSUE TITLE
Collapse project window

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#568]
We should make sure that the project window can be collapsed. Right now it takes a lot of screen space.

**Comment by lalalune** [comment]
@michaelsharpe idk, IMO it was better as a window. It always takes space, on my macbook it's quite a lot of space for information I don't really ever need.

**Comment by michaelsharpe** [comment]
@lalalune  We should open close on hotkey. The main benefit in my mind is a sticky way to open and navigate all your resources from one place, and not have it move around on every tab you open. If I double click a spell I want it to open a new tab and not move the file nav around in the space. 

It is a common pattern in code IDEs to navigate. Vscode has the sidebar for apps, the file drawer for files or other app data, and the main tabbed window area. I wanted to keep the pattern for both familiarity as well as a clear design hierarchy for interaction. 

From a design standpoint in terms of clear interaction hierarchy, a single spell file or prompt file would open up a new IDE tab so it makes sense to not have it inside the tab since it technically controls the opening of tabs.

I would also move all 'new spell, delete spell' functionality from the modal into the drawer to make it the main source of control for all assets in a project. 

It can be set to easily open and close on a hotkey like vscode as well so you can easily remove it if you don't navigate a ton of subspell and others resources. Though I also think that as we expand to other file types like a single prompt as per the design, it makes even more sense to keep them all available from one place to open and easily navigate. 

We could easily do both if you would rather it as a window. But I think in terms of easy top level project navigation it makes sense not inside individual tabs workspaces.

**Comment by michaelsharpe** [comment]
Agreed. Close on hotkey is super important. And drag to resize also crucial. Just like vscode.
