### ISSUE TITLE
Inputs are checkboxes, not dropdowns

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#718]
Right now we need lots of inputs and a switch between them to handle multiple input connectors. We should have a manifest of connectors loaded, with checkboxes for which inputs can be received. By default, all inputs should be included.

We can probably remove the input selector from the playtest window this way, and we can make Default/Playtest be one of the checkbox options on the Input node which the playtest sends to.

We can then probably have a "content" output for the inputs so that users don't need to destructure just to get the content. Could really simplify a lot of graphs.

<img width="716" alt="Screenshot 2023-04-24 at 4 13 09 PM" src="https://user-images.githubusercontent.com/18633264/234135327-a136bfeb-2721-4b53-8a8d-36fa9c997340.png">

NEW DESIGN
![image](https://user-images.githubusercontent.com/18633264/235385011-29bb41ad-c1e0-450c-b2be-de688c20a123.png)

**Comment by michaelsharpe** [comment]
Love this.  Only thing I would say is that the playtest is helpful to use in simulating different kinds of inputs, as well as changing up their data.  If you are working on how a discord input responds on a certain channel, you might want to modify the data for the Discord Input in the playtest to mock up a certain kind of event.

Also, since there can be multiple kinds of inputs on the spell, it is important to be able to target a specific input with the playtest. The dropdown actually auto-populates based on which inputs have been added.  It isn't so much about having a "playtest input" as an option as much as the playtest window being able to target any input on the graph.

Not sure how many people use this, but I use it a lot when I am developing, especially if I am doing anything with more than one input on it.

**Comment by lalalune** [comment]
I am imagining multiple inputs potentially, but they could have a different set of input types
